Добавление теста для TasksWorker
Select-IOS-Team/ToDoListCleanSwift pull request #34
Opened 2023-03-22 18:41 UTC by EvgeniMeleshin

Что было сделано?

Добавлен тест для TasksWorker

2023-03-23 06:59 UTC, Blissfulman requested changes

2023-03-23 06:59 UTC, Blissfulman commented on ToDoListCleanSwiftTests/UnitTests/TasksWorkerTests.swift
> +		)
То, что задачи должны быть отсортированы по какому-то признаку - это не ответственность воркера. Воркер не сортирует задачи и не контролирует их сортировку. Также он не контролирует порядок секций. Более того, он про это даже ничего не должен знать.

Задача тестируемого метода - преобразовать данные из массива кортежей в новую модель, сохранив их консистентность. Всё остальное его не касается. Ему без разницы какие именно задачи в секциях и в каком порядке, ему без разницы в каком порядке секции. Он просто должен переложить данные из одного вида в новый ничего не потеряв и не напутав.

Сейчас получается так, что если мы поменяем логику сортировки задач или порядок секций, то данный тест начнёт фейлиться, хотя воркер на самом деле будет правильно делать свою работу.

2023-03-23 06:59 UTC, Blissfulman commented on ToDoListCleanSwiftTests/UnitTests/TasksWorkerTests.swift
> +			importantTask2.toggleCompletetionState()
Для воркера без разницы какое состояние задач в массивах. Поэтому для данного теста нет необходимости в секцию выполненных задач класть именно выполненные. В данном случае подойдут любые задачи.

2023-03-23 07:07 UTC, Blissfulman commented on ToDoListCleanSwift/TasksScene/TasksWorker.swift
>  }
Перечисление типов секций следует называть в единственном числе (`SectionsType` вместо `SectionsTypes`)

2023-03-23 10:57 UTC, EvgeniMeleshin commented on ToDoListCleanSwift/TasksScene/TasksWorker.swift
>  }
fix

2023-03-23 10:57 UTC, EvgeniMeleshin commented on ToDoListCleanSwiftTests/UnitTests/TasksWorkerTests.swift
> +		)
fix

2023-03-23 10:57 UTC, EvgeniMeleshin commented on ToDoListCleanSwiftTests/UnitTests/TasksWorkerTests.swift
> +			importantTask2.toggleCompletetionState()
fix

2023-03-23 11:41 UTC, Blissfulman requested changes

2023-03-23 11:41 UTC, Blissfulman commented on ToDoListCleanSwiftTests/UnitTests/TasksWorkerTests.swift
> +		XCTAssertEqual(response.data[1].sectionTasks.count, 2, "Вторая секция должна содержать 2 задачи")
Лично мне не нравятся такие слишком привязанные к контексту теста сообщения в ассертах. Потому что когда на CI увидишь такое сообщение рядом с проваленным тестом, то, не зная контекст теста, не понятно с какой вообще стати должна быть одна задача. То есть всё равно надо лезть в реализацию теста, чтобы понять что не так. Тут конкретика не улучшает понимание, а, скорее, ухудшает.

Мне больше нравятся более абстрактные, но при это понятные без погружения в контекст теста сообщения, как например "Количество задач в секции не равно количеству задач этой же секции во входных данных".

Это не указание к исправлению, просто выразил своё мнение.

2023-03-23 11:41 UTC, Blissfulman commented on ToDoListCleanSwiftTests/UnitTests/TasksWorkerTests.swift
> +		)
Я бы здесь не привязывался к конкретным типам секций. Если представить, что секций было бы не 2, а 8, то не писать же 8 ассертов, когда можно просто сравнить какой набор секций был на входе, и какой на выходе.

А вообще, первые 4 `XCTAssertEqual` можно просто удалить, потому что все эти проверки полностью перекрываются пятым.

2023-03-23 12:09 UTC, EvgeniMeleshin commented on ToDoListCleanSwiftTests/UnitTests/TasksWorkerTests.swift
> +		)
Можно. У меня сначала так и было. Как раз для конкретики, в чем именно структура не соответствует ожидаемым данным и добавлял первые 4

2023-03-23 23:35 UTC, Blissfulman commented on ToDoListCleanSwiftTests/UnitTests/TasksWorkerTests.swift
> +		)
[Один из принципов](https://medium.com/@tasdikrahman/f-i-r-s-t-principles-of-testing-1a497acda8d6) написания тестов - их быстрота выполнения. Когда в приложении тысячи тестов, то такие дублирующие проверки будут значительно увеличивать общее время прохождения всех тестов. Поэтому, на мой взгляд, тут достаточно одной, проверяющей всё сразу проверки.

2023-03-25 15:21 UTC, Blissfulman approved these changes

2023-03-25 15:22 UTC, merged