M2L3. Добавить тесты для LoginWorker
Select-IOS-Team/ToDoListCleanSwift pull request #36
Opened 2023-03-25 04:38 UTC by SShliakhin

1. Надо проверить с корректными данными на выходе должны получить true - `LoginDTO(success: 1, login: login, lastLoginDate: Date())`
2. Надо проверить с неправильными данными на выходе должны получить false - `LoginDTO(success: 0, login: login, lastLoginDate: Date())`
3. Для этого создать шаблоны для корректного и неверного ответов и сравнить с выходом

2023-03-25 07:09 UTC, Blissfulman requested changes

2023-03-25 07:09 UTC, Blissfulman commented on ToDoListCleanSwiftTests/UnitTests/LoginScene/LoginWorkerTests.swift
В этом файле нужно добавить комменты с `// MARK: -` и комменты секций внутри тестов, как это описано в стайлгайде.

2023-03-25 07:09 UTC, Blissfulman commented on ToDoListCleanSwiftTests/UnitTests/LoginScene/LoginWorkerTests.swift
> +	private let invalidDataLoginDTO = LoginDTO(success: 0, login: "0")
Такие константы с данными для тестов мы выносим в приватное расширение. Посмотри как в других файлах уже сделано.

2023-03-25 08:23 UTC, SShliakhin commented on ToDoListCleanSwiftTests/UnitTests/LoginScene/LoginWorkerTests.swift
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/71236551/227706176-fcdc9963-8cd0-4f71-8930-5083baae2c7c.png">

2023-03-25 08:25 UTC, SShliakhin commented on ToDoListCleanSwiftTests/UnitTests/LoginScene/LoginWorkerTests.swift
> +	private let invalidDataLoginDTO = LoginDTO(success: 0, login: "0")
Пример сверху полностью соответсвуют двум твоим замечаниям, пример Кирилла из материалов к M2L4

2023-03-25 15:16 UTC, Blissfulman commented on ToDoListCleanSwiftTests/UnitTests/LoginScene/LoginWorkerTests.swift
Покажи мне источник, где было сказано, что вспомогательный материал Кирилл нужно использовать как образец стайлгайда.

Кирилл многократно повторял на лекциях и в разборе домашек, что следует придерживаться приложенных им стайлгайдов. Ты их читал?

2023-03-26 06:38 UTC, EvgeniMeleshin approved these changes

2023-03-26 15:35 UTC, Blissfulman commented on ToDoListCleanSwiftTests/UnitTests/LoginScene/LoginWorkerTests.swift
Поправил кодстайл

2023-03-26 15:35 UTC, Blissfulman commented on ToDoListCleanSwiftTests/UnitTests/LoginScene/LoginWorkerTests.swift
> +	private let invalidDataLoginDTO = LoginDTO(success: 0, login: "0")
Поправил кодстайл

2023-03-26 15:44 UTC, EvgeniMeleshin approved these changes

2023-03-26 15:49 UTC, Blissfulman approved these changes

2023-03-26 15:49 UTC, merged