Добавление тестов для TasksInteractor
Select-IOS-Team/ToDoListCleanSwift pull request #45
Opened 2023-03-25 15:49 UTC by EvgeniMeleshin

Что было сделано?

Добавлены тесты для TasksInteractor и вспомогательные двойники.
Переименован метод с fetchData()  на fetchSectionsWithTasksAndConvertToPresentModel() в TasksViewController.
Добавлены описания протокола ITasksPresenter и метода presentData.

2023-03-25 18:50 UTC, Blissfulman requested changes

2023-03-25 18:50 UTC, Blissfulman commented on ToDoListCleanSwiftTests/TasksScene/TasksInteractorTests.swift
> +	}
В этом методе интерактор помимо обращения к воркеру ещё два раза обращается к адаптеру. Это тоже необходимо проверять. А также необходимо проверить, что воркеру передаются корректные данные, полученные от адаптера.

2023-03-25 18:50 UTC, Blissfulman commented on ToDoListCleanSwiftTests/TasksScene/TasksInteractorTests.swift
> +	func test_didCheckboxTapped_withIndexPath_shouldBeCompleteTask() {
В этом методе также есть два обращения к адаптеру. Это нужно тестировать. Следует проверять, что в методы адаптера передаются корректные данные.

А также, в этом методе есть вызов второго метода интерактора. Это тоже тест должен проверить.

2023-03-25 18:50 UTC, Blissfulman commented on ToDoListCleanSwiftTests/TasksScene/TasksInteractorTests.swift
> +	}
Мне было сложнее понять код из-за того, что эта логика вынесена в данный метод. И назван он совсем неочевидно. Он создаёт задачу, помещает её в двойника, да ещё и возвращает задачу. Целых 3 действия, а называется при этом просто "создать заглушку".

При этом он вызывается в одном месте. Вполне нормальная практика делать это всё внутри теста. Это только улучшит читаемость теста.

2023-03-25 18:50 UTC, Blissfulman commented on ToDoListCleanSwiftTests/TasksScene/TasksInteractorTests.swift
> +		XCTAssertTrue(task.isCompleted, "Метод didCheckboxTapped не выполнил задачу")
Формулировка не очень удачная. Лучше "В задаче не произошла смена состояния выполненности".

Всё-таки задачи выполняют люди, а не методы))

2023-03-25 18:50 UTC, Blissfulman commented on ToDoListCleanSwift/TasksScene/TasksInteractor.swift
> +	func fetchSectionsWithTasksAndConvertToPresentModel() {
А почему решил так переименовать этот метод?

2023-03-25 18:50 UTC, Blissfulman commented on ToDoListCleanSwift.xcodeproj/project.pbxproj
> -				5E0E1B5C29CDC156004B70B2 /* RepositoryTests.swift in Sources */,
Кажется, что эта строка лишняя. И ещё в 4 местах встречается удаление этого файла.

2023-03-25 18:50 UTC, Blissfulman commented on ToDoListCleanSwift/TasksScene/TasksInteractor.swift
> +/// Интерактор,  получающий секции и задачи с помощью воркера для презентера
Обычно в таких комментах не пишут про зависимости, которые использует объект и про то. Это немного странно выглядит. Этих зависимостей может быть много и они могут меняться по ходу разработки. Тогда нужно будет постоянно не забывать актуализировать такой коммент. Это по-любому будет забываться.

Достаточно указать назначение объекта. Я бы, допустим, написал "Интерактор сцены списка задач". А то, что он взаимодействует с презентером, это понятно и так из знаний о шаблоне Clean Swift.

Вообще это требование делать док. комменты для объектов VIP цикла немного странное, на мой взгляд. Их назначение довольно очевидно из названия. Не припомню, чтоб где-то видел в реальных проектах комменты у них. Но раз уж есть такое требование, то что-то надо написать.

2023-03-26 05:45 UTC, Blissfulman commented on ToDoListCleanSwiftTests/TasksScene/TasksSceneDoubles/TasksPresenerSpy.swift
> +	// MARK: - Internal Properties
Желательно делать однообразные комменты, а именно, по стайлгайду второе слово в `// MARK: - ` с маленькой буквы

2023-03-26 06:46 UTC, EvgeniMeleshin commented on ToDoListCleanSwiftTests/TasksScene/TasksInteractorTests.swift
> +	private let presenter = TasksPresenterSpy()
Здесь нужны setUp и tearDown ?

2023-03-26 07:14 UTC, Blissfulman commented on ToDoListCleanSwiftTests/TasksScene/TasksInteractorTests.swift
> +	private let presenter = TasksPresenterSpy()
Не бери в расчёт этот коммент. Я не понял пока почему так, но потестировал и двойники сбрасывают своё состояние, хотя, как мне казалось, их должна держать сильная ссылка и они из-за этого должны оставаться одним и тем же объектом для всех тестов класса.

2023-03-26 07:51 UTC, Blissfulman commented on ToDoListCleanSwiftTests/TasksScene/TasksInteractorTests.swift
> +	private let presenter = TasksPresenterSpy()
Похоже, это происходит из-за какой-то оптимизации с распареллеливанием прогона тестов. Потому что когда я щас тестил получалось так, что под каждый тест инициализируется класс теста. Пока что не понимаю почему так. Спросил у Кирилла.

2023-03-26 09:33 UTC, EvgeniMeleshin commented on ToDoListCleanSwiftTests/TasksScene/TasksSceneDoubles/TestsWorkerSpy.swift
> +	func convertToTaskModelResponse(data: [(sectionType: ToDoListCleanSwift.SectionType, tasks: [ToDoListBusinessLogic.Task])]) -> ToDoListCleanSwift.TaskModel.Response { // swiftlint:disable:this line_
fix

2023-03-26 09:33 UTC, EvgeniMeleshin commented on ToDoListCleanSwiftTests/TasksScene/TasksInteractorTests.swift
> +	private let presenter = TasksPresenterSpy()
fix

2023-03-26 09:34 UTC, EvgeniMeleshin commented on ToDoListCleanSwiftTests/TasksScene/TasksInteractorTests.swift
> +		let sectionAdapter = SectionAdapter(taskManager: taskManagerSpy)
fix

2023-03-26 09:34 UTC, EvgeniMeleshin commented on ToDoListCleanSwiftTests/TasksScene/TasksInteractorTests.swift
> +	}
fix

2023-03-26 09:36 UTC, EvgeniMeleshin commented on ToDoListCleanSwift/TasksScene/TasksInteractor.swift
> +	func fetchSectionsWithTasksAndConvertToPresentModel() {
Решил конкретизировать что делает. Потому что в методе помимо получения еще методы

2023-03-26 09:37 UTC, EvgeniMeleshin commented on ToDoListCleanSwift/TasksScene/TasksInteractor.swift
> +/// Интерактор,  получающий секции и задачи с помощью воркера для презентера
fix

2023-03-26 09:37 UTC, EvgeniMeleshin commented on ToDoListCleanSwiftTests/TasksScene/TasksSceneDoubles/TasksPresenerSpy.swift
> +	// MARK: - Internal Properties
fix

2023-03-26 09:38 UTC, EvgeniMeleshin commented on ToDoListCleanSwiftTests/TasksScene/TasksInteractorTests.swift
> +		XCTAssertTrue(task.isCompleted, "Метод didCheckboxTapped не выполнил задачу")
fix

2023-03-26 16:41 UTC, EvgeniMeleshin commented on ToDoListCleanSwiftTests/TasksScene/TasksInteractorTests.swift
> +	}
fix

2023-03-26 16:42 UTC, EvgeniMeleshin commented on ToDoListCleanSwiftTests/TasksScene/TasksInteractorTests.swift
> +	func test_didCheckboxTapped_withIndexPath_shouldBeCompleteTask() {
fix

2023-03-29 06:07 UTC, Blissfulman requested changes

2023-03-29 09:24 UTC, EvgeniMeleshin commented on ToDoListCleanSwift/TasksScene/TasksInteractor.swift
> +	func fetchSectionsWithTasksAndConvertToPresentModel() {
fix

2023-03-29 09:24 UTC, EvgeniMeleshin commented on ToDoListCleanSwiftTests/TasksScene/TasksInteractorTests.swift
> +
fix

2023-03-29 09:24 UTC, EvgeniMeleshin commented on ToDoListCleanSwiftTests/TasksScene/TasksInteractorTests.swift
> +
fix

2023-03-29 09:25 UTC, EvgeniMeleshin commented on ToDoListCleanSwiftTests/TasksScene/TasksInteractorTests.swift
> +
fix

2023-03-29 09:25 UTC, EvgeniMeleshin commented on ToDoListCleanSwiftTests/TasksScene/TasksInteractorTests.swift
> +	}
fix

2023-03-29 12:03 UTC, Blissfulman approved these changes

2023-03-29 12:49 UTC, max-kubasov approved these changes

2023-03-29 15:07 UTC, merged