Изменение инъекций зависимостей
Select-IOS-Team/ToDoListCleanSwift pull request #79
Opened 2023-04-11 10:41 UTC by EvgeniMeleshin

# Что было сделано?

- изменены способы инъекций при создании TasksPresenter, TasksInteractor.

2023-04-11 17:16 UTC, Blissfulman requested changes

2023-04-12 05:43 UTC, EvgeniMeleshin commented on ToDoListCleanSwift/TasksScene/TasksPresenter.swift
>  	private var sectionsAdapter: ISectionsAdapter
fix

2023-04-12 05:43 UTC, EvgeniMeleshin commented on ToDoListCleanSwift/TasksScene/Managers/TasksDependenciesBuilder.swift
>  		return tasksViewController
fix

2023-04-12 18:56 UTC, Blissfulman commented on ToDoListCleanSwift/TasksScene/Managers/TasksDependenciesBuilder.swift
>  		return tasksViewController
А у вью контроллера инъекцию интерактора ещё через инициализатор надо добавить

2023-04-12 19:23 UTC, EvgeniMeleshin commented on ToDoListCleanSwift/TasksScene/Managers/TasksDependenciesBuilder.swift
>  		return tasksViewController
fix

2023-04-13 16:13 UTC, Blissfulman approved these changes

2023-04-13 20:02 UTC, merged